### ISSUE TITLE
[feat] 게시물 카테고리 생성

### ISSUE THREAD

**Issue by kdmin0706** [kdmin0706/AmKorea#24]
## ✨ Description
- 게시물 카테고리 생성

## 📢 To-Do
- [x] 게시물 카테고리 생성 API 구현
- [x] 게시물 카테고리 수정 API 구현
- [x] 게시물 카테고리 조회 API 구현
