### ISSUE TITLE
[feat]: #4 회원가입, 로그인 베이스 생성

### ISSUE THREAD

**Issue by kdmin0706** [kdmin0706/AmKorea#4]
## ✨ Description
> 회원가입 및 로그인을 위한 베이스 API 구현

## 📢 To-Do
- [x] 회원가입 시에 사용하는 signUp API 구현
- [x] 로그인 시에 사용하는 signIn API 구현
- [x] 로그인의 경우 로그인 완료 후 jwt 키를 받아야하기 때문에 임시 void 형식으로 완료만 체크
